{
 "title": "Welcome Dashboard",
 "time": { "from": "2025-06-02T06:25:04.807Z", "to": "2025-06-03T06:25:04.807Z" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "metrics", "query": { "query": "label_values(__name__)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 19, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background-color: lightblue; padding: 20px; text-align: center; color: black;\">\r\n  <h1>InsightAI</h1>\r\n</div>\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "options": {
    "content": "<div style=\"padding: 20px; overflow: hidden; text-align: center;\">\n  <a href=\"http://localhost:3000/d/0b61a1f0-9a66-4439-892a-09b89f7cab03/metrics\" style=\"color: cyan; text-decoration: none;\">\n    <h2>Explore Metrics</h2>\n  </a>\n</div>\n"
   }
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Alerts",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 4 },
     "targets": [
      {
       "parser": "backend",
       "root_selector": "data.alerts.labels",
       "source": "url",
       "summarizeBy": "severity",
       "type": "json",
       "url": "/api/v1/alerts",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Alerts",
     "type": "table",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 4 },
     "targets": [
      {
       "parser": "backend",
       "root_selector": "data.alerts.labels",
       "source": "url",
       "type": "json",
       "url": "/api/v1/alerts",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Average E2E Request Latency",
   "type": "stat",
   "description": "End to end request latency measured in seconds.",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(vllm_e2e_request_latency_seconds_sum[$__rate_interval])\n/\nrate(vllm_e2e_request_latency_seconds_count[$__rate_interval])",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "E2E Request Latency",
   "type": "stat",
   "description": "End to end request latency measured in seconds.",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm_e2e_request_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm_e2e_request_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm_e2e_request_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm_e2e_request_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "rate(vllm:e2e_request_latency_seconds_sum{model_name=\"$model_name\"}[$__rate_interval])\n/\nrate(vllm:e2e_request_latency_seconds_count{model_name=\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Total number of successful requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (vllm_request_success_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token Throughput",
   "type": "stat",
   "description": "Number of tokens processed per second",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(vllm_prompt_tokens_total[$__rate_interval])",
     "legendFormat": "Prompt Tokens/Sec"
    },
    {
     "expr": "rate(vllm_prompt_tokens_total[$__rate_interval])",
     "legendFormat": "Generation Tokens/Sec"
    }
   ]
  },
  {
   "title": "Cache Utilization",
   "type": "stat",
   "description": "Percentage of used cache blocks by vLLM.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vllm:gpu_cache_usage_perc{model_name=\"$model_name\"}",
     "legendFormat": "GPU Cache Usage"
    },
    { "expr": "vllm_gpu_cache_usage_perc", "legendFormat": "CPU Cache Usage" }
   ]
  }
 ]
}