# config.yaml
global:
  resolve_timeout: 30s

route:
  group_wait: 0s
  group_interval: 30s
  repeat_interval: 30s
  group_by: ['alertname', 'instance', 'job']
  receiver: slack-notifications-default

  routes:
    - match:
        severity: critical
      receiver: slack-notifications-critical

receivers:
  - name: slack-notifications-default
    slack_configs: 
      - api_url: ''
        channel: '#project-insightai_minions'
        text: |-
          *{{ .CommonAnnotations.summary }}*
          {{ .CommonAnnotations.description }}
          This from InsightAI🔍

  - name: slack-notifications-critical
    slack_configs:
      - api_url: ''
        channel: '#insightai-critical-alerts'
        text: |-
          *{{ .CommonAnnotations.summary }}*
          {{ .CommonAnnotations.description }}
          This from InsightAI🔍