# docker-compose.yaml
version: "3"

services:
  prometheus:
    image: prom/prometheus:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"     # allow a direct connection from container to the local machine
    ports:
      - "0.0.0.0:9090:9090"   # the default port used by Prometheus
    volumes:
      - ${PWD}/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml # mount Prometheus config file

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "0.0.0.0:3000:3000" # the default port used by Grafana
  
  vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    gpus: all
    ports:
      - "0.0.0.0:8000:8000" 
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface # mount Hugging Face cache directory
    command: ["--host", "0.0.0.0", "--model", "gpt2"]
